# -*- coding: utf-8 -*-
"""Resimayarlama

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OTj7bdhSUPSbnAqXPbmJXxT_l8ua8sqV
"""

# opencv install etmeyi unutma!!!!!!!!!!!
import cv2
import numpy as np


def resim_ayar(image, contrast, highlights, shadows, whites, blacks):
    # Resmi alıyor
    img = cv2.imread(image)

    ayar = img.astype(float)
    ayar = ayar * contrast
    ayar = np.clip(ayar, 0, 255)

    # Highlights
    ayar += (highlights * (255 - ayar)) / 255.0
    ayar = np.clip(ayar, 0, 255)

    # Shadows
    ayar *= (255.0 / np.max(ayar))
    ayar -= (shadows * ayar) / 255.0
    ayar = np.clip(ayar, 0, 255)

    # Whites ve blacks
    ayar += (whites * (255 - ayar)) / 255.0
    ayar -= (blacks * ayar) / 255.0
    ayar = np.clip(ayar, 0, 255)

    return ayar.astype(np.uint8)


# Kullanıcıdan resimin yolunu istiyor
resim = input("Lütfen resim dosyasının yolunu giriniz: ")

# Kullanıcıdan ayar değerlerini istiyor
contrast_value = float(input("Contrast ayarı giriniz: "))
highlights_value = float(input("Highlights ayarı giriniz: "))
shadows_value = float(input("Shadows ayarı giriniz : "))
whites_value = float(input("Whites ayarı giriniz :"))
blacks_value = float(input("Blacks ayarı giriniz : "))

# Resim ayarlamayı uygulama
resim_ayar = resim_ayar(resim, contrast_value, highlights_value, shadows_value, whites_value, blacks_value)

# Sonucu gösterme
cv2.imshow('ayarlanmış resim', resim_ayar)
cv2.waitKey(0)
cv2.destroyAllWindows()